# Project: Ex3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../Ex3/main.o
LINKOBJ  = ../Ex3/main.o
LIBS     = -L"C:/ProgramFiles/Dev-Cpp/MinGW64/lib" -L"C:/ProgramFiles/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/ProgramFiles/Dev-Cpp/MinGW64/include" -I"C:/ProgramFiles/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/ProgramFiles/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/ProgramFiles/Dev-Cpp/MinGW64/include" -I"C:/ProgramFiles/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/ProgramFiles/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/ProgramFiles/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Ex3.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

../Ex3/main.o: ../Ex3/main.c
	$(CC) -c ../Ex3/main.c -o ../Ex3/main.o $(CFLAGS)
